### ISSUE TITLE
在选择课程的时候报错

### ISSUE THREAD

**Issue by wangyitu** [abusizhishen/51cto-video-download#6]
请选择:2
以下是您购买的课程：
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    fun(ss)
  File "E:\51cto\Course.py", line 7, in run
    lesson.Lesson(ss).set_course_id_by_course_list().lesson_list().download()
  File "E:\51cto\cto\lesson.py", line 190, in set_course_id_by_course_list
    print "课程ID:%d, 课程名称:%s" % (course['id'], course['title'])
LookupError: unknown encoding: cp65001

**Comment by wangyitu** [comment]
改成chcp 936 ，开始乱码，输入课程id后出现如下错误：
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    fun(ss)
  File "E:\51cto\Course.py", line 7, in run
    lesson.Lesson(ss).set_course_id_by_course_list().lesson_list().download()
  File "E:\51cto\cto\lesson.py", line 168, in download
    tools.download(file_name, urls, func_decode)
  File "E:\51cto\cto\tools.py", line 42, in download
    data = func_decode(data)
  File "E:\51cto\cto\lesson.py", line 166, in func_decode
    return decory_video.Video().decory(play_key, str(lesson_id), video_data)
  File "E:\51cto\cto\decory_video.py", line 18, in decory
    cipher = AES.new(key, AES.MODE_ECB, iv)
  File "D:\Python27\lib\site-packages\Crypto\Cipher\AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "D:\Python27\lib\site-packages\Crypto\Cipher\AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "D:\Python27\lib\site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long

**Comment by Tsunami-Song** [comment]
模仿楼主的脚本我写了个自动化脚本，输入ID即可下载视频：
https://v.qq.com/x/page/n0974x7fld0.html
